routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', "PostController@index")->name('home');

// Route Model Binding
Route::get('/blog/{post}', "PostController@show")->name('blog.show');

Route::get('/category/{category}', "PostController@category")->name('category');

Auth::routes();

Route::get('/admin', 'Backend\AdminController@index')->name('dashboard');
Route::get('/admin/posts', 'Backend\PostController@index')->name('posts.index');

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'slug', 'body', 'excerpt', 'image', 'author_id'];

    /**
     * @var array
     * Add published_at to date object
     */
    protected $dates = ['published_at'];

    /**
     * @return string
     * Create accessor to get post image url
     */
    public function getImageUrlAttribute()
    {
        // default no found image
        $imageUrl = asset("img/no_image.png");

        if(!is_null($this->image)){
            $imagePath = public_path(). '/img/'. $this->image;
            if(file_exists($imagePath)){
                $imageUrl = asset('img/'. $this->image);
            }
        }
        return $imageUrl;
    }

    /**
     * @return string
     * Create accessor to get post thumbnail url
     */
    public function getImageThumbUrlAttribute()
    {
        // default no found image
        $thumbUrl = asset("img/no_thumb.png");

        if(!is_null($this->thumbnail)){
            $thumbePath = public_path(). '/img/'. $this->thumbnail;
            if(file_exists($thumbePath)){
                $thumbUrl = asset('img/'. $this->thumbnail);
            }
        }
        return $thumbUrl;
    }


    /**
     * relation ship with user(author)
     */
    public function author()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * create scope for created_at
     */
    public function scopeLatestFirst($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    /**
     * create scope for popular posts
     */
    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    /**
     *display the posts status
     */
    public function displayStatus()
    {
       if($this->published_at == null){
           return "<span class='label label-warning'>Draft</span>";
           // isFuture() is Carbon method
       }elseif($this->published_at && $this->published_at->isFuture()){
           return "<span class='label label-info'>Scheduled</span>";
       }else{
           return "<span class='label label-success'>Published</span>";
       }
    }


    /**
     * @return mixed
     * Create published_at accessor
     */
    public function getDateAttribute()
    {
        return (is_null($this->published_at)) ? '' : $this->published_at->diffForHumans();
    }

    /**
     * create scope for created_at
     */
    public function scopePublished($query)
    {
        return $query->where('published_at', "<=" , Carbon::now());
    }

    /**
     * Relation ship with category model
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

}

resources/views/partials/_sidebar.blade.php
<div class="col-md-4">
    <aside class="right-sidebar">
        <!-- Search
        <div class="search-widget">
            <div class="input-group">
                <input type="text" class="form-control input-lg" placeholder="Search for...">
                <span class="input-group-btn">
                            <button class="btn btn-lg btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                          </span>
            </div>
        </div>
        -->
        <div class="widget">
            <div class="widget-heading">
                <h4>Categories</h4>
            </div>
            <div class="widget-body">
                <ul class="categories">
                    @foreach($categories as $category)
                    <li>
                        <a href={{ route('category', $category->slug) }}><i class="fa fa-angle-right"></i>&nbsp;{{ $category->name }}</a>
                        <span class="badge pull-right">{{ $category->posts->count() }}</span>
                    </li>
                    @endforeach
                </ul>
            </div>
        </div>

        <div class="widget">
            <div class="widget-heading">
                <h4>Popular Posts</h4>
            </div>
            <div class="widget-body">
                <ul class="popular-posts">
                    @foreach($popularPosts as $popPost)
                    <li>
                        <div class="post-image">
                            <a href="{{ route('blog.show', $popPost->slug) }}">
                                <img src="{{ $popPost->image_thumb_url }}" />
                            </a>
                        </div>
                        <div class="post-body">
                            <h6><a href="{{ route('blog.show', $popPost->slug) }}">{{ $popPost->title }}</a></h6>
                            <div class="post-meta">
                                <span>{{ $popPost->date }}</span>
                            </div>
                        </div>
                    </li>
                    @endforeach
                </ul>
            </div>
        </div>
        <!-- Tags
        <div class="widget">
            <div class="widget-heading">
                <h4>Tags</h4>
            </div>
            <div class="widget-body">
                <ul class="tags">
                    <li><a href="#">PHP</a></li>
                    <li><a href="#">Codeigniter</a></li>
                    <li><a href="#">Yii</a></li>
                </ul>
            </div>
        </div>
        -->
    </aside>
</div>