routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', "PostController@index")->name('home');

// Route Model Binding
Route::get('/blog/{post}', "PostController@show")->name('blog.show');

Route::get('/category/{category}', "PostController@category")->name('category');

Auth::routes();

Route::get('/admin', 'Backend\AdminController@index')->name('dashboard');
Route::get('/admin/posts', 'Backend\PostController@index')->name('posts.index');

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'slug', 'body', 'excerpt', 'image', 'author_id'];

    /**
     * @var array
     * Add published_at to date object
     */
    protected $dates = ['published_at'];

    /**
     * @return string
     * Create accessor to get post image url
     */
    public function getImageUrlAttribute()
    {
        // default no found image
        $imageUrl = asset("img/no_image.png");

        if(!is_null($this->image)){
            $imagePath = public_path(). '/img/'. $this->image;
            if(file_exists($imagePath)){
                $imageUrl = asset('img/'. $this->image);
            }
        }
        return $imageUrl;
    }

    /**
     * @return string
     * Create accessor to get post thumbnail url
     */
    public function getImageThumbUrlAttribute()
    {
        // default no found image
        $thumbUrl = asset("img/no_thumb.png");

        if(!is_null($this->thumbnail)){
            $thumbePath = public_path(). '/img/'. $this->thumbnail;
            if(file_exists($thumbePath)){
                $thumbUrl = asset('img/'. $this->thumbnail);
            }
        }
        return $thumbUrl;
    }


    /**
     * relation ship with user(author)
     */
    public function author()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * create scope for created_at
     */
    public function scopeLatestFirst($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    /**
     * create scope for popular posts
     */
    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    /**
     *display the posts status
     */
    public function displayStatus()
    {
       if($this->published_at == null){
           return "<span class='label label-warning'>Draft</span>";
           // isFuture() is Carbon method
       }elseif($this->published_at && $this->published_at->isFuture()){
           return "<span class='label label-info'>Scheduled</span>";
       }else{
           return "<span class='label label-success'>Published</span>";
       }
    }


    /**
     * @return mixed
     * Create published_at accessor
     */
    public function getDateAttribute()
    {
        return (is_null($this->published_at)) ? '' : $this->published_at->diffForHumans();
    }

    /**
     * create scope for created_at
     */
    public function scopePublished($query)
    {
        return $query->where('published_at', "<=" , Carbon::now());
    }

    /**
     * Relation ship with category model
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

}

resources/views/blog/comments.blade.php
<article class="post-comments">
    <h3><i class="fa fa-comments"></i> 5 Comments</h3>

    <div class="comment-body padding-10">
        <ul class="comments-list">
            <li class="comment-item">
                <div class="comment-heading clearfix">
                    <div class="comment-author-meta">
                        <h4>John Doe <small>January 14, 2016</small></h4>
                    </div>
                </div>
                <div class="comment-content">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                    <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                </div>
            </li>

            <li class="comment-item">
                <div class="comment-heading clearfix">
                    <div class="comment-author-meta">
                        <h4>John Doe <small>January 14, 2016</small></h4>
                    </div>
                </div>
                <div class="comment-content">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                    <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

                    <ul class="comments-list-children">
                        <li class="comment-item">
                            <div class="comment-heading clearfix">
                                <div class="comment-author-meta">
                                    <h4>John Doe <small>January 14, 2016</small></h4>
                                </div>
                            </div>
                            <div class="comment-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                            </div>
                        </li>

                        <li class="comment-item">
                            <div class="comment-heading clearfix">
                                <div class="comment-author-meta">
                                    <h4>John Doe <small>January 14, 2016</small></h4>
                                </div>
                            </div>
                            <div class="comment-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

                                <ul class="comments-list-children">
                                    <li class="comment-item">
                                        <div class="comment-heading clearfix">
                                            <div class="comment-author-meta">
                                                <h4>John Doe <small>January 14, 2016</small></h4>
                                            </div>
                                        </div>
                                        <div class="comment-content">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                            <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>

    </div>

    <div class="comment-footer padding-10">
        <h3>Leave a comment</h3>
        <form>
            <div class="form-group required">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" class="form-control">
            </div>
            <div class="form-group required">
                <label for="email">Email</label>
                <input type="text" name="email" id="email" class="form-control">
            </div>
            <div class="form-group">
                <label for="website">Website</label>
                <input type="text" name="website" id="website" class="form-control">
            </div>
            <div class="form-group required">
                <label for="comment">Comment</label>
                <textarea name="comment" id="comment" rows="6" class="form-control"></textarea>
            </div>
            <div class="clearfix">
                <div class="pull-left">
                    <button type="submit" class="btn btn-lg btn-success">Submit</button>
                </div>
                <div class="pull-right">
                    <p class="text-muted">
                        <span class="required">*</span>
                        <em>Indicates required fields</em>
                    </p>
                </div>
            </div>
        </form>
    </div>

</article>

resources/views/blog/index.blade.php
@extends('layouts.master')
@section('title') {{ env('APP_NAME') }} @endsection
@section("content")
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                @if($posts->count() != 0)
                    @foreach($posts as $post)
                        <article class="post-ite">
                            <div class="post-item-image">
                                <a href="{{ route('blog.show', $post->slug) }}">
                                    <img src="{{ $post->image_url }}" alt="{{ $post->slug }}">
                                </a>
                            </div>
                            <div class="post-item-body">
                                <div class="padding-10">
                                    <h2><a href="{{ route('blog.show', $post->slug) }}">{{ $post->title }}</a></h2>
                                    <p>{!! $post->body !!}</p>
                                </div>

                                <div class="post-meta padding-10 clearfix">
                                    <div class="pull-left">
                                        <ul class="post-meta-group">
                                            <li><i class="fa fa-user"></i><strong> {{ $post->author->name }}</strong></li>
                                            <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                                            <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug) }}">{{ $post->category->name }}</a></li>
                                            <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
                                        </ul>
                                    </div>
                                    <div class="pull-right">
                                        <a href="post.html">Continue Reading &raquo;</a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    @endforeach
                    {{ $posts->links() }}
                @else
                    <div class="alert alert-warning">
                        Nothing found
                    </div>
                @endif
            </div>
@include("partials._sidebar")
        </div>
    </div>
@endsection

resources/views/blog/show.blade.php
@extends('layouts.master')
@section('title') Blog | {{ $post->title }} @endsection
@section("content")
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <article class="post-item post-detail">
                    <div class="post-item-image">
                        <img src="{{ $post->image_url}}" alt="{{ $post->title }}">
                    </div>

                    <div class="post-item-body">
                        <div class="padding-10">
                            <h1>{{ $post->title }}</h1>

                            <div class="post-meta no-border">
                                <ul class="post-meta-group">
                                    <li><i class="fa fa-user"></i><strong> {{ $post->author->name }}</strong></li>
                                    <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                                    <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug) }}"> {{ $post->category->name }}</a></li>
                                    <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
                                </ul>
                            </div>
                            <p>{!! $post->body !!}</p>
                        </div>
                    </div>
                </article>

                <article class="post-author padding-10">
                    <div class="media">
                        <div class="media-left">
                            <a href="#">
                                <img alt="Author 1" src="{{ asset("img/author.jpg") }}" class="media-object">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><strong>{{ $post->author->name }}</strong></h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad aut sunt cum, mollitia excepturi neque sint magnam minus aliquam, voluptatem, labore quis praesentium eum quae dolorum temporibus consequuntur! Non.</p>
                        </div>
                    </div>
                </article>

                {{-- Cooments --}}
            </div>
            @include("partials._sidebar")
        </div>
    </div>

@endsection